### ISSUE TITLE
Helper does not work in Meteor 1.2

### ISSUE THREAD

**Issue by faceyspacey** [chuangbo/meteor-marked#21]
A fix I found is to do this: 

````
return HTML.Raw(marked(content.trim()));
````

i.e. ```trim``` the content before passing it to ```marked``` etc.

**Comment by gadicc** [comment]
That's surprising.. I was tempted to just go with such an easy fix but I think trimming the unprocessed markdown could have unintended consequences (e.g. consider text that begins with code using indentation rather than a code fence).

But also, I wasn't able to reproduce this.  Does this affect every string for you or just some strings?  Can you give an example and the exact error you get?

**Comment by faceyspacey** [comment]
It was actually my bad. I wasnt using markdown returned from a helper or data context, but rather just pasted in markdown to see if it would work. The markdown was indented (so it nests nicely with the surrounding HTML). Once i removed the indents so it was flush with the left side, it worked. Might be worth documenting that--perhaps it's just common knowledge I wasn't privy to (never done much with markdown or this sorta thing). Anyway, that's all I got.
